Repository PrestaShop/ps_searchbar, pull requests merged in 2022-01, with the labels that each got.

#44 Update Github Actions
  .github/workflows/build-release.yml
Labels: enhancement

#43 Improved displaying of the search bar placeholder
  ps_searchbar.css
Labels: QA ✔️

#45 Set tab property
  ps_searchbar.php
Labels: bug
